# Generated by Django 5.2.15 on 2026-06-04 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Attivo'), ('paused', 'In pausa'), ('to_invoice', 'Da fatturare'), ('overdue', 'Insoluto'), ('closed', 'Concluso')], default='active', max_length=30)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('drive_folder_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='workspaces.workspace')),
            ],
        ),
    ]
