# Generated by Django 5.2.15 on 2026-06-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='client',
            name='administrative_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_role',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='client',
            name='pec',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_prefix',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='sdi_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='client',
            name='theme_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='vat_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
