# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_client_address_client_administrative_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="drive_folder_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="client",
            name="drive_sync_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="drive_sync_status",
            field=models.CharField(
                choices=[("pending", "In attesa"), ("synced", "Sincronizzato"), ("failed", "Errore")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
