# Generated by Codex on 2026-06-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceDriveSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("google_account_email", models.EmailField(blank=True, max_length=254)),
                ("drive_id", models.CharField(blank=True, max_length=120)),
                ("clients_root_folder_name", models.CharField(default="clients", max_length=80)),
                ("clients_root_folder_id", models.CharField(blank=True, max_length=120)),
                ("clients_root_folder_url", models.URLField(blank=True)),
                ("service_account_info", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drive_settings",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workspace Drive settings",
                "verbose_name_plural": "Workspace Drive settings",
            },
        ),
    ]
