# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_workspacedrivesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacedrivesettings",
            name="google_access_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workspacedrivesettings",
            name="google_refresh_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="workspacedrivesettings",
            name="google_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
